project:
  type: book

book:
  title: "test"
  author: "Norah Jones"
  date: "13/11/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - test.qmd
    - summary.qmd
    - references.qmd

  sidebar:
    style: "docked"
    search: false
    contents:
      - text: "Introduction Page"
        href: intro.qmd
      - text: "Basics"
        href: summary.qmd
      - text: "A Test"
        href: test.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand

  pdf:
    documentclass: scrreprt



